spring:
  datasource:
    hikari: #https://github.com/brettwooldridge/HikariCP#configuration-knobs-baby
      jdbcUrl: jdbc:mariadb://localhost:3306/ddalivery_db?useUnicode=true&characterEncoding=utf8
      username: bnids
      password: qldps_2020
      driver-class-name: org.mariadb.jdbc.Driver
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 40
      maximumPoolSize: 40
  jpa:
    database: mysql
    show-sql: false
    generate-ddl: false

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  flyway:
    enabled: false
    encoding: UTF-8

  h2:
    console:
      enabled: false

